### ISSUE TITLE
Support Windows Server 2019

### ISSUE THREAD

**Issue by rnelson0** [kreeuwijk/vmtools_win#10]
As best I can tell, WS 2019 support is practically the same as WS 2016, and possibly only `metadata.json` needs updated. However, I do not currently have 2019 available to test with, though my company is looking at using it soon, hence this issue. Please let me know how I can help.

**Comment by kreeuwijk** [comment]
Testing now

**Comment by kreeuwijk** [comment]
Windows 2019 support has been added!
