### ISSUE TITLE
VMtools  Compare version.pp issue

### ISSUE THREAD

**Issue by grk1986** [kreeuwijk/vmtools_win#12]
Hi,

I am new to puppet and was testing vmtools installation on my pilot environment, I was using this VMtools module quite some time and succesfully able to install/upgrade, however all of sudden i am started seeing the comparision version issue on the module, i downloaded the module 1.1.0 version. Looks like the desired version cannot convert to Numeric, can you help me on this.

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: The value '' cannot be converted to Numeric. (file: /etc/puppetlabs/code/environments/production/modules/vmtools_win/functions/compare_version.pp, line: 40, column: 47)

**Comment by kreeuwijk** [comment]
Hi @grk1986, I can take a look for you.
Can you share the values of the following facts for me, for a node that experiences this problem?
* vmtools_win_online_file
* vmtools_win_online_version
* vmtools_win_version

**Comment by kreeuwijk** [comment]
And are you setting the module to use the latest version from VMware online, or are you specifying your own package?

**Comment by benohara** [comment]
I believe https://github.com/kreeuwijk/vmtools_win/pull/13 fixes this

**Comment by kreeuwijk** [comment]
Assumed fixed in v1.1.1
