### ISSUE TITLE
r10k - Forge module copied with bad permissions

### ISSUE THREAD

**Issue by UnicodeTreason** [kreeuwijk/vmtools_win#2]
Issue:
When using r10k to copy the module from the Forge into Puppet Open Source the module is copied onto the system with only root having access to the files. This prevents the Foreman user from being able to use the files.

Testing:
* Download vmtools_win module via Forge: Bad Permissions
* Download vmtools_win module directly from git: Works Fine
* Download other modules (badgerious-windows_env, martezr-windows_disable_ipv6) via Forge: Works Fine

Misc:
Im pretty green when it comes to Puppet, Foreman, Linux etc. so am entirely stumped by this issue.
But as I can only replicate it with this module and only via Forge I can only assume its an issue with the Forge uploaded copy.

Any further troubleshooting I can do to assist in tracking down the issue let me know.

**Comment by kreeuwijk** [comment]
Thanks, I'll investigate why this is happening...

**Comment by kreeuwijk** [comment]
There is a new 1.0.4 version on the Forge now with corrected permissions. I've created an internal ticket to flag this undesired behavior with permissions getting inherited into the Forge tarball. Thanks for informing us!
