### ISSUE TITLE
Fix incorrect documentation on the puppet forge

### ISSUE THREAD

**Issue by MichaelGerhart** [kreeuwijk/vmtools_win#5]
The puppet forge documentation references the class name as 'vmwaretools', while that is incorrect. The documentation should reference the class name 'vmtools_win'.

**Comment by kreeuwijk** [comment]
Hi Michael,
that's indeed the case, my bad. I'll have a look at updating the documentation on the forge without pushing a new version.

**Comment by kreeuwijk** [comment]
Fixed now!
