### ISSUE TITLE
Compare_version function fails compilation using simple "include vmtools_win" usage on Windows server 2016

### ISSUE THREAD

**Issue by ginodambrosio** [kreeuwijk/vmtools_win#7]
With most basic "include vmtools_win" usage on Windows 2016 server if $facts['vmtools_win_version'] is not defined the init.pp logic still runs this the install_needed function:

    if vmtools_win::install_needed($download_from_vmware, $minimum_version_level, $selfprovided_install_version) 

which when interpolated using default hiera values becomes:

    if vmtools_win::install_needed(true, 3, 'None')

Somehow the compare_version function is invoked for deployments on windows servers without any previous VMWare tools such that:

    $comparison = vmtools_win::compare_version($facts['vmtools_win_version'], $selfprovided_install_version)

is set to:

    $comparison = vmtools_win::compare_version(undef, 'None')

Catalog compilation borks when comparison is attempted of the undefined $facts['vmtools_win_version'] to 'None'. When the vmtools_win_version.rb facter script is run there will be nothing listed matching "VMWare Tools" under HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall.  :

C:\WINDOWS\system32>puppet agent -t
Notice: Local environment: 'production' doesn't match server specified node environment 'gino', switching agent to 'gino'.
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: The value '' cannot be converted to Numeric. (file: /etc/puppetlabs/code/environments/gino/modules/vmtools_win/functions/compare_version.pp, line: 40, column: 14) on node puppnode-dev-t1.dev
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by ginodambrosio** [comment]
vmtools_win v1.0.5 doesn't exhibit this issue.

**Comment by kreeuwijk** [comment]
Fixed fully in v1.0.7
Thanks for posting!
