### ISSUE TITLE
Dead URL

### ISSUE THREAD

**Issue by genebean** [kreeuwijk/vmtools_win#9]
While trying to debug why this is failing to work, I found this line:
https://github.com/kreeuwijk/vmtools_win/blob/393d089449c5e9dbade3163e7780d70656524bdc/lib/vmtools_win/vmtools_win_online_file.ps1#L1
https://packages.vmware.com/tools/releases/latest/ no longer contains a `windows` directory... best I can tell, it looks like this should switch to pulling from Chocolatey a la `choco install vmware-tools`

**Comment by rnelson0** [comment]
https://packages.vmware.com/tools/releases/latest/windows/x64/ is now back (and https redirects to it), possibly an intermittent issue or a problem following redirects?

**Comment by kreeuwijk** [comment]
Seems this was a hiccup at VMware, closing issue for now.
